=== feruccio/Xml1/src/com/haurylenka/projects/xml1/resources/schedule.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" 
	targetNamespace="http://www.example.org/schedule" 
	xmlns:tns="http://www.example.org/schedule" 
	elementFormDefault="qualified">
	
	<element name="schedule">
		<complexType>
			<sequence maxOccurs="unbounded">
				<element name="itinerary" type="tns:Itinerary"></element>
			</sequence>
		</complexType>
	</element>
	
	<complexType name="Itinerary">
		<sequence>
			<element name="from" type="tns:Airport"></element>
			<element name="to" type="tns:Airport"></element>
			<element name="periodicity" type="tns:Periodicity"></element>
		</sequence>
		<attribute name="number" type="string"></attribute>
	</complexType>
	
	<complexType name="Airport">
		<sequence>
			<element name="name" type="string"></element>
			<element name="city" type="string"></element>
		</sequence>
	</complexType>
	
	<complexType name="Periodicity">
		<sequence>
			<element name="departure" type="time"></element>
			<element name="arrival" type="time"></element>
			<element name="nextDay" type="boolean"></element>
			<element name="gate" type="string"></element>
			<element name="prices" type="tns:Prices"></element>
		</sequence>
		<attribute name="type" type="tns:PeriodType"></attribute>
		<attribute name="ordinal" type="positiveInteger"></attribute>
	</complexType>
	
	<complexType name="Prices">
		<sequence maxOccurs="unbounded">
			<element name="price" type="tns:Price"></element>
		</sequence>
	</complexType>
	
	<complexType name="Price">
		<sequence>
			<element name="seatType" type="tns:SeatType"></element>
			<element name="base" type="positiveInteger"></element>
		</sequence>
	</complexType>
	
	<simpleType name="SeatType">
		<restriction base="string">
			<enumeration value="economy"></enumeration>
			<enumeration value="first"></enumeration>
			<enumeration value="business"></enumeration>
		</restriction>
	</simpleType>
	
	<simpleType name="PeriodType">
		<restriction base="string">
			<enumeration value="minute"></enumeration>
			<enumeration value="hour"></enumeration>
			<enumeration value="day"></enumeration>
			<enumeration value="week"></enumeration>
			<enumeration value="fortnight"></enumeration>
			<enumeration value="month"></enumeration>
			<enumeration value="year"></enumeration>
		</restriction>
	</simpleType>
	
</schema>

=== feruccio/Xml1/src/com/haurylenka/projects/xml1/resources/schedule.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<schedule xmlns="http://www.example.org/schedule" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/schedule schedule.xsd">
    <itinerary number="AB1234">
        <from>
            <name>JFK</name>
            <city>New York</city>
        </from>
        <to>
            <name>Minsk2</name>
            <city>Minsk</city>
        </to>
        <periodicity ordinal="1" type="day">
            <departure>12:52:01</departure>
            <arrival>21:52:01</arrival>
            <nextDay>false</nextDay>
            <gate>A2</gate>
            <prices>
                <price>
                    <seatType>economy</seatType>
                    <base>300</base>
                </price>
                <price>
                    <seatType>business</seatType>
                    <base>500</base>
                </price>
                <price>
                    <seatType>first</seatType>
                    <base>400</base>
                </price>
            </prices>
        </periodicity>
    </itinerary>
    <itinerary number="AB1234">
        <from>
            <name>JFK</name>
            <city>New York</city>
        </from>
        <to>
            <name>Minsk2</name>
            <city>Minsk</city>
        </to>
        <periodicity ordinal="1" type="day">
            <departure>12:52:01</departure>
            <arrival>21:52:01</arrival>
            <nextDay>false</nextDay>
            <gate>A2</gate>
            <prices>
                <price>
                    <seatType>economy</seatType>
                    <base>300</base>
                </price>
                <price>
                    <seatType>business</seatType>
                    <base>500</base>
                </price>
                <price>
                    <seatType>first</seatType>
                    <base>400</base>
                </price>
            </prices>
        </periodicity>
    </itinerary>
</schedule>
